name: repo_sync

on: [ push, delete, create ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: net-engine/github-repository-sync-action@v1
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          target_repo_url: git@gitee.com:juan-lavender/cosbrowser.git
