name: repo_sync

on: [ push, delete, create ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          target_repo_url: https://gitee.com/juan-lavender/cosbrowser.git
