name: repo_sync

on: [ push, delete, create ]

jobs:
  repo_sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          des_repository: juan-lavender/https://gitee.com/juan-lavender/cosbrowser.git
