name: repo_sync

on: [ push, delete, create ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          repository: https://gitee.com/juan-lavender/cosbrowser.git
